/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.clases.Ecuacion;
import Modelo.clases.Linea;
import Modelo.clases.Validacion;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultCellEditor;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableModel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.xy.XYSeries;
import org.jfree.data.xy.XYSeriesCollection;

/**
 *
 * @author ALEXANDER
 */
public class metodoGraficoVista extends javax.swing.JFrame {

    /**
     * Creates new form metodoGraficoVista
     */
    public metodoGraficoVista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        comboRestricciones = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaRestricciones = new javax.swing.JTable();
        botonGraficar = new javax.swing.JButton();
        panelGrafica = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        textFuncionX1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        textFuncionX2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        comboRestricciones.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        comboRestricciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboRestriccionesActionPerformed(evt);
            }
        });

        jLabel1.setText("Cantidad de restricciones");

        tablaRestricciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tablaRestricciones);

        botonGraficar.setText("Solucionar");
        botonGraficar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGraficarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelGraficaLayout = new javax.swing.GroupLayout(panelGrafica);
        panelGrafica.setLayout(panelGraficaLayout);
        panelGraficaLayout.setHorizontalGroup(
            panelGraficaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 416, Short.MAX_VALUE)
        );
        panelGraficaLayout.setVerticalGroup(
            panelGraficaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 234, Short.MAX_VALUE)
        );

        jLabel2.setText("Restricciones");

        jLabel3.setText("Función objetivo");

        textFuncionX1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFuncionX1ActionPerformed(evt);
            }
        });
        textFuncionX1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textFuncionX1KeyTyped(evt);
            }
        });

        jLabel4.setText("+");

        textFuncionX2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFuncionX2ActionPerformed(evt);
            }
        });
        textFuncionX2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textFuncionX2KeyTyped(evt);
            }
        });

        jLabel5.setText("X1");

        jLabel6.setText("X2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(panelGrafica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(125, 125, 125))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(jLabel1)
                        .addGap(36, 36, 36)
                        .addComponent(comboRestricciones, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(72, 72, 72)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(textFuncionX1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(textFuncionX2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(124, 124, 124)
                                .addComponent(jLabel5)
                                .addGap(76, 76, 76)
                                .addComponent(jLabel6))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(432, 432, 432)
                        .addComponent(botonGraficar)))
                .addContainerGap(174, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(comboRestricciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(textFuncionX1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(textFuncionX2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonGraficar)
                .addGap(32, 32, 32)
                .addComponent(panelGrafica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    int cantidadRestrecciones = 0;
    Validacion validaciones = new Validacion();

    public JComboBox Simplex() {
        JComboBox comboBox = new JComboBox();
        comboBox.addItem("<=");
        comboBox.addItem(">=");
        comboBox.addItem("=");
        return comboBox;
    }

    private void comboRestriccionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboRestriccionesActionPerformed
        cantidadRestrecciones = comboRestricciones.getSelectedIndex() + 1;
        String columnNames[] = {"X1", "X2", "Signo", "Resultado"};
        Object data[][] = new Object[cantidadRestrecciones][4];

        for (int i = 0; i < cantidadRestrecciones; i++) {
            data[i][0] = "";
            data[i][1] = "";
            data[i][2] = "";
            data[i][3] = "";
        }
        TableModel datosTabla = new DefaultTableModel(data, columnNames);
        tablaRestricciones.setModel(datosTabla);
        TableColumn signo = tablaRestricciones.getColumnModel().getColumn(tablaRestricciones.getColumnCount() - 2);
        signo.setCellEditor(new DefaultCellEditor(Simplex()));
    }//GEN-LAST:event_comboRestriccionesActionPerformed

    private void botonGraficarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGraficarActionPerformed
        List<Ecuacion> restricciones = new ArrayList<>();
        Ecuacion ecuacionObjetivo = new Ecuacion();
        ecuacionObjetivo.setVariableX1((-1) * Double.valueOf(textFuncionX1.getText()));
        ecuacionObjetivo.setVariableX2((-1) * Double.valueOf(textFuncionX2.getText()));
        ecuacionObjetivo.setTipoEcuacion("Objetivo");
        restricciones.add(ecuacionObjetivo);

        for (int i = 0; i < cantidadRestrecciones; i++) {
            Ecuacion ecuacion = new Ecuacion();
            ecuacion.setVariableX1(Double.valueOf(tablaRestricciones.getModel().getValueAt(i, tablaRestricciones.getModel().getColumnCount() - 4).toString()));
            ecuacion.setVariableX2(Double.valueOf(tablaRestricciones.getModel().getValueAt(i, tablaRestricciones.getModel().getColumnCount() - 3).toString()));
            ecuacion.setSigno(tablaRestricciones.getModel().getValueAt(i, tablaRestricciones.getModel().getColumnCount() - 2).toString());
            ecuacion.setResultado(Double.valueOf(tablaRestricciones.getModel().getValueAt(i, tablaRestricciones.getModel().getColumnCount() - 1).toString()));
            restricciones.add(ecuacion);
        }
        obtenerRectas(restricciones);
        validaciones.gaussMaxi(restricciones, restricciones.size(), 2);

    }//GEN-LAST:event_botonGraficarActionPerformed

    private void textFuncionX1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFuncionX1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFuncionX1ActionPerformed

    private void textFuncionX2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFuncionX2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFuncionX2ActionPerformed

    private void textFuncionX1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textFuncionX1KeyTyped
        if (!validaciones.validarCaracteres(evt)) {
            JOptionPane.showMessageDialog(this, "Solo numeros permitidos");
        }
    }//GEN-LAST:event_textFuncionX1KeyTyped

    private void textFuncionX2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textFuncionX2KeyTyped
        if (!validaciones.validarCaracteres(evt)) {
            JOptionPane.showMessageDialog(this, "Solo numeros permitidos");
        }
    }//GEN-LAST:event_textFuncionX2KeyTyped

    private void obtenerRectas(List<Ecuacion> ecuaciones) {
        List<Linea> rectas = new ArrayList<>();
        for (Ecuacion ecuacion : ecuaciones) {
            Linea recta = new Linea();
            if (!"Objetivo".equals(ecuacion.getTipoEcuacion())) {
                recta.setCoordenadaY1(0.0);
                recta.setCoordenadaX2(0.0);
                if (ecuacion.getVariableX1() != 0) {
                    recta.setCoordenadaX1(ecuacion.getResultado() / ecuacion.getVariableX1());
                } else {
                    recta.setCoordenadaX1(ecuacion.getResultado() + 100);
                    recta.setCoordenadaY1(ecuacion.getResultado());
                }
                if (ecuacion.getVariableX2() != 0) {
                    recta.setCoordenadaY2(ecuacion.getResultado() / ecuacion.getVariableX2());
                } else {
                    recta.setCoordenadaY2(ecuacion.getResultado() + 100);
                    recta.setCoordenadaX2(ecuacion.getResultado());
                }
                rectas.add(recta);
            } else {
                recta.setCoordenadaY1(0.0);
                recta.setCoordenadaX2(0.0);
                if (ecuacion.getVariableX1() != 0) {
                    recta.setCoordenadaX1(10000 / (ecuacion.getVariableX1() * -1));
                } else {
                    recta.setCoordenadaX1(500.0);
                    recta.setCoordenadaY1(500.0);
                }
                if (ecuacion.getVariableX2() != 0) {
                    recta.setCoordenadaY2(10000 / (ecuacion.getVariableX2() * -1));
                } else {
                    recta.setCoordenadaY2(500.0);
                    recta.setCoordenadaX2(500.0);
                }
                recta.setTipo("Objetivo");
                rectas.add(recta);

            }
        }

        List<XYSeries> listaObjectosSeries = new ArrayList<>();
        XYSeries oSeries;

        XYSeriesCollection oDataset = new XYSeriesCollection();
        int contador = 0;
        for (int i = 0; i < rectas.size(); i++) {
            if (rectas.get(i).getTipo() != "Objetivo") {
                contador++;
                oSeries = new XYSeries("Restricción" + contador);
                oSeries.add(rectas.get(i).getCoordenadaX1(), rectas.get(i).getCoordenadaY1());
                oSeries.add(rectas.get(i).getCoordenadaX2(), rectas.get(i).getCoordenadaY2());
                oDataset.addSeries(oSeries);
                listaObjectosSeries.add(oSeries);
            } else {
                oSeries = new XYSeries("Función Objetivo");
                oSeries.add(rectas.get(i).getCoordenadaX1(), rectas.get(i).getCoordenadaY1());
                oSeries.add(rectas.get(i).getCoordenadaX2(), rectas.get(i).getCoordenadaY2());
                oDataset.addSeries(oSeries);
                listaObjectosSeries.add(oSeries);
            }
        }

        JFreeChart oChart = ChartFactory.createXYLineChart("MÉTODO GRÁFICO", "EJE X", "EJE Y ", oDataset, PlotOrientation.VERTICAL, true, false, false);
        ChartPanel oPanel = new ChartPanel(oChart);

        panelGrafica.setLayout(new java.awt.BorderLayout());
        panelGrafica.add(oPanel);
        panelGrafica.validate();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(metodoGraficoVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(metodoGraficoVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(metodoGraficoVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(metodoGraficoVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new metodoGraficoVista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonGraficar;
    private javax.swing.JComboBox<String> comboRestricciones;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelGrafica;
    private javax.swing.JTable tablaRestricciones;
    private javax.swing.JTextField textFuncionX1;
    private javax.swing.JTextField textFuncionX2;
    // End of variables declaration//GEN-END:variables
}
